backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/uploads" # Media files will be stored in the repo under content/uploads (to make the image processing work we have to use this technique to spoof the images being page resources
public_folder: "/uploads" # The src attribute for uploaded media will begin with this

collections:
  - label: "Index Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/_index.html"
        fields:
          - {label: Display Title, name: display_title, widget: string}
          - {label: Site Description, name: description, widget: text}
          - {label: Who We Are Block Text, name: who_we_are, widget: text}
          - {label: News Banner Heading, name: news_banner_heading, widget: string}
          - {label: News Banner Blurb, name: news_banner_blurb, widget: string}
          - {label: News Banner Link, name: news_banner_link, widget: string}
          - label: "Who We Are Image"
            name: "who_we_are_image"
            widget: "image"
            default: "/uploads/wherry-group-592w.jpg"
            media_library:
              config:
                multiple: false
          - label: "Hero Image"
            name: "hero_image"
            widget: "image"
            default: "/uploads/dnd-hero-3400w.jpg"
            media_library:
              config:
                multiple: false
          - label: "News Banner Image"
            name: "news_banner_image"
            widget: "image"
            default: "/uploads/wherry-seminar-table.png"
            media_library:
              config:
                multiple: false
      - label: "About Page"
        name: "about"
        file: "content/about/_index.html"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection

    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

    fields: # The fields for each document, usually in front matter

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        required: false
        widget: "datetime"

      - label: "Draft"
        name: "draft"
        required: false
        widget: "boolean"
        default: true

      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"

      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"

      - label: "Keywords"
        name: "keywords"
        required: false
        widget: "list"

      - label: "Auto Thumbnail Image"
        name: "autoThumbnailImage"
        required: false
        widget: "boolean"
        default: true

      - label: "Thumbnail Image Position"
        name: "thumbnailImagePosition"
        required: false
        widget: "select"
        options: ["left", "top", "right"]

      - label: "Thumbnail Image"
        name: "thumbnailImage"
        required: false
        widget: "image"

      - label: "Cover Image"
        name: "coverImage"
        required: false
        widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
